Issue #SB-13164 feat:play and akka end to end integration
project-sunbird/sunbird-user-service pull request #11
Opened 2019-06-19 11:00 UTC by amit-tarento

2019-06-19 13:11 UTC, indrajra requested changes

2019-06-19 13:11 UTC, indrajra commented on actor-service/src/main/java/org/sunbird/actor/core/ActorCache.java
> + * This class will maintain the cache of actor reference.
Please add a comment line that it today does not handle remote actor references. Recall our discussion - we need this to be discussed with other partner teams too.

2019-06-19 13:11 UTC, indrajra commented on actor-service/src/main/java/org/sunbird/actor/core/BaseActor.java
> +            match(ArithmeticException.class, e -> {
Put a todo stating that this will need to be removed. It is good to have this sample until others get used to this.

2019-06-19 13:11 UTC, indrajra commented on user-org-actor/src/main/java/org/sunbird/user/UserCreateActor.java
> +        ProjectLogger.log("UserCreateActor: onReceive called for operation: " + request.getOperation(), LoggerEnum.INFO);
Can you lift this line to the base class? I think you already have one; perhaps remove "BaseClass" literal from the log line. Then it must be fine.

2019-06-19 13:11 UTC, indrajra commented on user-org-util/src/main/java/org/sunbird/request/ExecutionContext.java
> +  // TODO move Response out of context
is this TODO valid? Just asking if you've inserted. Lets retain TODOs that are inserted now (by us).

2019-06-19 13:11 UTC, indrajra commented on user-org-util/src/main/java/org/sunbird/request/ExecutionContext.java
> +      if ("".equals(serviceCallPath)) serviceCallPath = value;
If we are using this, then there is no good use of StringUtils from apache-common...I asked another one to remove this dependency itself. Could we get rid of it?

2019-06-24 12:11 UTC, amit-tarento commented on actor-service/src/main/java/org/sunbird/actor/core/ActorCache.java
> + * This class will maintain the cache of actor reference.
Added the comment

2019-06-24 12:12 UTC, amit-tarento commented on actor-service/src/main/java/org/sunbird/actor/core/BaseActor.java
> +            match(ArithmeticException.class, e -> {
As of now i removed the code for supervision strategy

2019-06-24 12:12 UTC, amit-tarento commented on user-org-actor/src/main/java/org/sunbird/user/UserCreateActor.java
> +        ProjectLogger.log("UserCreateActor: onReceive called for operation: " + request.getOperation(), LoggerEnum.INFO);
Done

2019-06-24 12:13 UTC, amit-tarento commented on user-org-util/src/main/java/org/sunbird/request/ExecutionContext.java
> +  // TODO move Response out of context
This is the old code from sunbird-learning service. Need to refactor this class

2019-06-24 12:14 UTC, amit-tarento commented on user-org-util/src/main/java/org/sunbird/request/ExecutionContext.java
> +      if ("".equals(serviceCallPath)) serviceCallPath = value;
Using StringUtils will make our code much cleaner and bug free , if used efficiently

2019-06-25 05:00 UTC, indrajra commented on user-org-util/src/main/java/org/sunbird/request/ExecutionContext.java
> +      if ("".equals(serviceCallPath)) serviceCallPath = value;
We discussed - we will have a task for this separately (for all code reused).

2019-06-25 05:02 UTC, indrajra approved these changes

2019-06-25 05:02 UTC, indrajra commented on actor-service/src/main/java/org/sunbird/actor/core/ActorService.java
> +        if (instance == null)
needs fix - marked as tbd shortly.

2019-06-25 05:03 UTC, merged